### ISSUE TITLE
Optional `std` in optional dependencies

### ISSUE THREAD

**Issue by dhardy** [rust-random/getrandom#110]
#106 makes `std` optional.

To [quote myself](https://github.com/rust-random/getrandom/pull/106#issuecomment-533490913) (to create an open issue):

> I foresee an issue here: `rand_core` has optional dependencies on `getrandom` *and* `std`, and now needs to depend on `getrandom/std` *only* if both are enabled. I'm not sure how to do that. See [here](https://github.com/rustsim/nalgebra/pull/622#issuecomment-531805268) where the same issue came up recently.

This is really a Cargo issue IMO, but something we may have to find a workaround to.

**Comment by josephlr** [comment]
Is this an issue if the `rand_core`'s `std` feature unconditionally enables `getrandom`? That seems to be what it does currently.

**Comment by newpavlov** [comment]
No, the problem is that `rand_core` uses `getrandom`'s `std` feature for converting `getrandom::Error` into `Box<dyn std::error::Error>`. We want to enable `std` feature for `getrandom` only if both `getrandom` and `std` features are enabled for `rand_core`, but unfortunately AFAIK it's impossible to define such relation right now, since `std = ["getrandom/std"]` will enable `getrandom` optional dependency. So we either can't enable `std` feature for `getrandom` or we always depend on `getrandom` with an enabled `std` feature.

But actually it does not matter for `rand_core v0.5`, since it [always enables](https://github.com/rust-random/rand/blob/master/rand_core/Cargo.toml#L22) `getrandom` with an enabled `std` feature.
