### ISSUE TITLE
Infallible getrandom API

### ISSUE THREAD

**Issue by alex** [rust-random/getrandom#19]
First, thanks for splitting out this functionality from `rand`/`rand_os`, it's very pleasant to use!

Second, I'm wondering if it'd make sense to consider including ` getrandom_infallible()` API that was basically `getrandom().expect("...")`. That's what most (all?) of my callers are doing ATM.

**Comment by newpavlov** [comment]
Why not simply use `getrandom(buf).unwrap()`? It's 2 characters shorter than `getrandom_infallible(buf)`. Alternatively soon you could use `OsRng.fill_bytes(buf)`.

I guess we could include a wrapper function (with a better name), but personally I prefer the current simple API which does not hide possibility of errors. Though if @dhardy would prefer to add such function I will not be against doing it.

**Comment by alex** [comment]
I used `expect()` instead of `unwrap()`, and eyah, it works great!

I didn't really have a use case for actually handling the error in any of my code, so I figured I should file this. If there's no interest that's ok by me!

**Comment by dhardy** [comment]
I believe the only reason not to use `unwrap` if you don't plan on returning an error value is because it merely uses a generic error message. But getting a backtrace from a panic is quite easy.

For better formatting you could do something like `.unwrap_or_else(|e| panic!("{}", e))`. We *could* add a method for this, but I don't see very much value?

**Comment by newpavlov** [comment]
I think we can close this issue?
