### ISSUE TITLE
Hermit is not currently supported by getrandom

### ISSUE THREAD

**Issue by josephlr** [rust-random/getrandom#199]
[Hermitcore](https://hermitcore.org/) is a unikernel OS, written in Rust, with [Tier 3 `libstd` support](https://doc.rust-lang.org/beta/rustc/platform-support.html#tier-3) for `aarch64-unknown-hermit` and `x86_64-unknown-hermit`.

See #198 and #183 for previous attempts at this.

Other PRs/issues of note:
  - My initial question to the Hermit folks about their RNG: https://github.com/hermitcore/rusty-hermit/issues/63
  - Change that adds Cryptographic RNG support to Hermit (x86 only): https://github.com/hermitcore/libhermit-rs/pull/98
  - Change that exposes RNG APIs as part of `hermit-abi`: https://github.com/hermitcore/rusty-hermit/pull/64
  - Making `hermit-abi` always `no_std`: hermitcore/rusty-hermit#103
  - Fix for the RDRAND implementation in `libhermit-rs`: https://github.com/hermitcore/libhermit-rs/pull/154
  - Feature request to have hermit use a buffer-based API: hermitcore/libhermit-rs#143

We should figure out:
  - How/when we want to add support to `getrandom`
  - Is the existing [`secure_rand64` API](https://hermitcore.github.io/rusty-hermit/hermit_abi/fn.secure_rand64.html) sufficient?
  - Hermit's RNG apis current don't work on `aarch64`, is that an issue?

**Comment by newpavlov** [comment]
>Hermit's RNG apis current don't work on aarch64, is that an issue?

Yes, it's an issue, since it causes workarounds like [this](https://github.com/rust-lang/rust/blob/582566d513ee4e1e33c9f6f98d913e6a025b6283/library/std/Cargo.toml#L26-L28). In user code it can be worked around slightly more elegantly using the `custom` feature, but we can not rely on it in `std`. Note that currently Hermit's `std` simply [uses](https://github.com/rust-lang/rust/blob/master/library/std/src/sys/hermit/mod.rs#L86-L89) a constant seed on all targets.

**Comment by josephlr** [comment]
I think the most reasonable approach here is the following:

1. Simply add support for hermit using their `secure_rand64` API and the `hermit-abi` crate. Given that hermit is a unikernel, I don't see any reason to push them for a buffer-based API (so hermitcore/libhermit-rs#143 isn't too important).
2. Keep the [`aarch64`+`hermit` workaround](https://github.com/rust-lang/rust/pull/80149/files#diff-3116c5ac1b13231b1577d36240ffbfae46cace14b42422d1f02f520046e38600R2887) in https://github.com/rust-lang/rust/pull/80149 for now.
3. Eventually, change `std`'s use of getrandom to emit a fallback seed if the `getrandom` function fails.

**Comment by newpavlov** [comment]
>Given that hermit is a unikernel, I don't see any reason to push them for a buffer-based API

Buffer-based API is not important here, it's the fact that Hermit randomness API always fails on ARM targets. To say the least, it's not normal and should be fixed.

>The std implementation will then return a fallback seed, preserving the existing behavior.

I don't think it's a good behavior for all targets. It effectively means introduction of potential silent failures just because one target has an always failing randomness source.

**Comment by josephlr** [comment]
Fixed by #333 333
