### ISSUE TITLE
[REQUEST] Disable all baked-in implementations, via features

### ISSUE THREAD

**Issue by becominginsane** [rust-random/getrandom#207]
It would be very nice if one was able to disable all "default" implementations and only rely on custom made...

I'm facing an issue where I'm building on a particular version of linux where I don't have access for example to `open`, so I made a custom function and I'd like to use that, but the lib would still try to link against `open`... 
I guess I can stub it out but would that fallback to the registered custom one?

**Comment by newpavlov** [comment]
It can cause security issues, so it's unlikely we will do it. The easiest way for you will be to simply replace `getrandom` with your own crate via the [`[patch]`](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section) section.

**Comment by josephlr** [comment]
I agree with @newpavlov here, we don't want to allow users to override the randomness implementations on "supported" targets (like `x864_64-unknown-linux-gnu`).

An approach that might work for you is to have a [custom target](https://rust-embedded.github.io/embedonomicon/custom-target.html) for your builds that makes it clear that you aren't building for Linux exactly. This means you won't be able to use `std` (but can use `core` and `alloc`). I don't think this will be too much of a problem because if you can't use the `open` and `getrandom` syscalls, you likely won't be able to use `std` with any success.

**Comment by becominginsane** [comment]
yeah neither `std` or `alloc` anyways...
