### ISSUE TITLE
Usage with wasm-pack?

### ISSUE THREAD

**Issue by drwpow** [rust-random/getrandom#208]
Hello! I’m a beginner just playing around with wasm-pack. While loading a crate that uses `rand`, I try to run `wasm-pack build --target web` and get the following error:

```
error: target is not supported, for more information see: https://docs.rs/getrandom/#unsupported-targets
   --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.2.2/src/lib.rs:213:9
    |
213 | /         compile_error!("target is not supported, for more information see: \
214 | |                         https://docs.rs/getrandom/#unsupported-targets");
    | |_________________________________________________________________________^
```

It seems that neither `--target web` nor `--target nodejs`, which I’m trying to use (I’m trying to compile WASM both for web and Node).

Is there any chance that this project could support either target? Happy to help contribute if work is needed.

**Comment by newpavlov** [comment]
Have you read the crate documentation? It clearly [states](https://docs.rs/getrandom/0.2.2/getrandom/#webassembly-support) that for `wasm32-unknown-unknow` you have to enable the `js` feature, i.e. you should add `getrandom = { version = "0.2", features = ["js"] }` to your list of dependencies.

**Comment by josephlr** [comment]
@newpavlov I think @drwpow is confused about two conflicting uses of `--target` here.

It seems like `wasm-pack` uses [`--target` to select the preferred web environment](https://rustwasm.github.io/wasm-pack/book/commands/build.html#target) (`nodejs`, `web`, `bundler`, etc...). This is different that the use of `--target` by `rustc` and `cargo`, where it's the normal concept of a Rust target.

Basically, despite whatever `--target` you pass to `wasm-pack` you will end up using the Rust target of `wasm32-unknown-unknown`. In that case, @newpavlov is right, you need to enable the "js" feature so that `getrandom` knows that JS bindings exist.

@drwpow does that answer your question?

**Comment by newpavlov** [comment]
Could it be worth to use an alternative compiler error message for `wasm32-unknown-unknown`? Something like:
```
the wasm32-unknown-unknown target is not supported by default, for more information see:
https://docs.rs/getrandom/#webassembly-support and https://docs.rs/getrandom/#unsupported-targets
```

**Comment by josephlr** [comment]
> Could it be worth to use an alternative compile-time error message for `wasm32-unknown-unknown`?

I think that's a great idea (we could also mention `wasm-pack` in our docs).

**Comment by drwpow** [comment]
>Basically, despite whatever `--target` you pass to `wasm-pack` you will end up using the Rust target of `wasm32-unknown-unknown`. In that case, @newpavlov is right, you need to enable the "js" feature so that `getrandom` knows that JS bindings exist.
>
>@drwpow does that answer your question?

Ah yes! That makes sense. Thanks for the explanation.

I’m not using `getrandom` directly; I’m using a crate which depends on `rand`, which depends on this. This is where the error message originated from, but now I can see if one (or both) parent crates can enable this flag (or add this flag if missing). Thank you!

**Comment by AuroraLantean** [comment]
https://stackoverflow.com/questions/71734501/error-adding-custom-rpcs-for-custom-pallet-substrate

**Comment by wk3368** [comment]
As described in https://docs.rs/getrandom/latest/getrandom/

```
To enable the js Cargo feature, add the following to the dependencies section in your Cargo.toml file:

```
[dependencies]
getrandom = { version = "0.2", features = ["js"] }
```

This can be done even if getrandom is not a direct dependency.
```

I fixed this problem in my case while getrandom is not a direct dependency.

**Comment by ManojJiSharma** [comment]
Thanks @wk3368 that works for me!!!

**Comment by gustawdaniel** [comment]
in latest version

```
getrandom = { version = "0.3", features = ["wasm_js"] }
```

and then build with

```
RUSTFLAGS='--cfg getrandom_backend="wasm_js"' wasm-pack build
```

docs: https://docs.rs/getrandom/latest/getrandom/#webassembly-support

**Comment by toolness** [comment]
Thanks @gustawdaniel!

Your suggestion worked on one of my computers, but on another computer, my `wasm-pack` command was _still_ failing, and I was very confused.

I eventually realized that `wasm-pack` wasn't finding `wasm-bindgen-cli`, so it was trying to build it--but with the `RUSTFLAGS` environment variable set, it was trying to build it (a CLI application) with the `wasm_js` backend, which was failing, telling me I needed to enable the `wasm_js` feature.  This was very confusing, of course, because I _did_ enable that feature in my project--but `wasm-pack` was trying to build `wasm-bindgen-cli`, _not_ my project!

Once I realized this, I ran `cargo install wasm-bindgen-cli` separately, without any `RUSTFLAGS` environment variable set.  After that, running `wasm-pack` on my project worked fine.

I think maybe another workaround that might have fixed my situation (though I didn't try it) would have been to define the backend in a target-specific way in my `.cargo/config.toml`:

```toml
[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']
```

Because that configuration tells cargo to only set `rustflags` when the target is WASM, I am guessing that `wasm-pack`'s building of `wasm-bindgen-cli` wouldn't have exploded, but I'm not sure.

**Comment by Mon-ius** [comment]
just fisrt perform,

```sh
cargo install wasm-pack
cargo install wasm-bindgen-cli
```

Add,
```sh
[dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }
```

Then perform,
```
RUSTFLAGS='--cfg getrandom_backend="wasm_js"' wasm-pack build --target web
```
