### ISSUE TITLE
Are there any plans to add support for ARM targets (`thumbv7em-none-eabi` and others)?

### ISSUE THREAD

**Issue by fjarri** [rust-random/getrandom#219]
Sorry if this was discussed before, I couldn't find a corresponding issue. The `thumb*` targets are mentioned in [Rust Embedded book](https://docs.rust-embedded.org/book/start/qemu.html) and are the go-to for people starting embedded programming in Rust.

**Comment by josephlr** [comment]
I would like to know more about this target because, as far as I know, before ARMv8.5 there is no standardized way to get randomness on ARM processors. With the [release of Armv8.5-A](https://community.arm.com/developer/ip-products/processors/b/processors-ip-blog/posts/arm-a-profile-architecture-2018-developments-armv85a), AArch64 now has the [`RNDR` Architecture Register](https://developer.arm.com/documentation/ddi0595/2021-03/AArch64-Registers/RNDR--Random-Number?lang=en), which is basically ARM's version of RDRAND. It can even be used from userspace (called EL0 on AArch64).

However, this doesn't completely mean you are out of luck. Per [this section of our documentation](https://docs.rs/getrandom/0.2.3/getrandom/#custom-implementations), you can register a custom RNG handler with [`register_custom_getrandom!()`](https://docs.rs/getrandom/0.2.3/getrandom/macro.register_custom_getrandom.html). Once registered, this handler will be invoked by `getrandom` for RNG generation. This even works if `getrandom` is an _indirect_ dependency of your crate.

However, this does mean that you have to implement the RNG yourself. I have heard that many ARM SoCs have an on-chip RNG. But I've also heard that the design, security, and interface vary from Chip to Chip. However, I'm not very familiar with the non-standard ARM extensions, so I'd love to know more.

**Comment by fjarri** [comment]
Frankly, I do not know much about it myself, I just had requests from some users of my library for the support of this target. I thought that perhaps it was a planned feature and wanted to register an interest, but it seems that it is either very hard or even impossible to implement. I suppose the best way for me to handle it would be to proceed with your recommendation in https://github.com/nucypher/rust-umbral/issues/13, and this issue may be better off closed.

**Comment by josephlr** [comment]
Sounds good, thanks for bringing this up!
