### ISSUE TITLE
Add function which returns random array?

### ISSUE THREAD

**Issue by newpavlov** [rust-random/getrandom#281]
`getrandom` is often used to generate seed for user-space PRNG. #279 adds unsafe raw API which allows to remove redundant initialization of buffers. So I wonder if it could be worth to introduce the following safe wrappers:
```rust
pub fn getrandom_array<const N: usize>() -> Result<[u8; N], Error> {
    let mut buf = mem::MaybeUninit::<[u8; N]>::uninit();
    unsafe { getrandom_raw(buf.as_mut_ptr().cast(), N).map(|()| buf.assume_init()) }
}

pub fn getrandom_u32() -> Result<u32, Error> {
    getrandom_array().map(u32::from_ne_bytes)
}

pub fn getrandom_u64() -> Result<u64, Error> {
    getrandom_array().map(u64::from_ne_bytes)
}

// and maybe other wrappers for u16, u128, i32, i64, etc.
```

Of course, `getrandom_array` implies MSRV bump to 1.51, which could be done in sync with [`rand v0.9`](https://github.com/rust-random/rand/issues/1165).

**Comment by josephlr** [comment]
Personally, I don't think adding the API is worth dealing with a v0.3 or some sort of conditional compilation. This seems like the type of thing best left to `rand_core`. The API suggested here is essentially just [`impl RngCore for OsRng`](https://github.com/rust-random/rand/blob/b73640705d6714509f8ceccc49e8df996fa19f51/rand_core/src/os.rs#L52)

I think it would b e better to just change the rand_core implementation to be:
```rust
impl RngCore for OsRng {
    fn next_u32(&mut self) -> u32 {
        let mut u = mem::MaybeUninit::uninit();
        unsafe { getrandom_raw(u.as_mut_ptr().cast(), mem::size_of::<u32>()) }.unwrap();
        u.assume_init()
    }

    fn next_u64(&mut self) -> u64 {
        let mut u = mem::MaybeUninit::uninit();
        unsafe { getrandom_raw(u.as_mut_ptr().cast(), mem::size_of::<u64>()) }.unwrap();
        u.assume_init()
    }

    fn fill_bytes(&mut self, dest: &mut [u8]) {
        self.try_fill_bytes(dest).unwrap()
    }

    fn try_fill_bytes(&mut self, dest: &mut [u8]) -> Result<(), Error> {
        Ok(getrandom(dest)?)
    }
}
```

**Comment by newpavlov** [comment]
I think the methods could be useful for users which depend directly on `getrandom` without relying on `rand_core`. Plus it would reduce amount of `unsafe` in `rand_core` (by moving it to `getrandom`, but still).

I agree that probably it's not worth to release together with `rand v0.9`, but it could be worth to consider during the next breaking release (which could be 1.0, not 0.3).

**Comment by briansmith** [comment]
> ```rust
> pub fn getrandom_array<const N: usize>() -> Result<[u8; N], Error> {
>     let mut buf = mem::MaybeUninit::<[u8; N]>::uninit();
>     unsafe { getrandom_raw(buf.as_mut_ptr().cast(), N).map(|()| buf.assume_init()) }
> }
````

This is exactly what https://github.com/rust-lang/rust/pull/80149 would best use.

> ```
> pub fn getrandom_u32() -> Result<u32, Error> {
>     getrandom_array().map(u32::from_ne_bytes)
> }
> 
> pub fn getrandom_u64() -> Result<u64, Error> {
>     getrandom_array().map(u64::from_ne_bytes)
> }
> ```

I'm not really sure that these are justified to add.

**Comment by briansmith** [comment]
> ```rust
> pub fn getrandom_u32() -> Result<u32, Error> {
>     getrandom_array().map(u32::from_ne_bytes)
> }
> 
> pub fn getrandom_u64() -> Result<u64, Error> {
>     getrandom_array().map(u64::from_ne_bytes)
> }
> ```

I looked more deeply into some applications that would use these and I found that having functions that return `u32`/`u64`/etc. don't cover many of the use cases. In all the cases I cared about, I needed different or additional mappings, e.g. mapping to `Wrapping<T>` or equivalent. Further, it seems very rare to generate a single random `u128` or any smaller value; instead, we usually need to generate an array of such values. So I suggest we avoid implementing those or at least consider them out of scope of this feature.

**Comment by briansmith** [comment]
I support adding such an API. My goal for advocating for such functionality is to eliminate all uses of `unsafe` from typical uses of common consumers of `getrandom`. Accordingly, I did some more research to advance this.

Consider this basic function, which I think is the one most agreeable to the most people:

```rust
#[inline(always)]
pub fn getrandm_array<const N: usize>() -> Result<[u8; N], Error> {
    let mut uninit: MaybeUninit<[u8; N]> = MaybeUninit::uninit();
    // TODO: `uninit.as_bytes_mut()` when that is available.
    {
        // SAFETY: MaybeUninit<u8> is always valid, even for padding bytes
        let as_bytes_mut = unsafe {
            core::slice::from_raw_parts_mut(uninit.as_mut_ptr() as *mut MaybeUninit<u8>, N)
        };
        getrandom::getrandom_uninit(as_bytes_mut)?;
    }
    // SAFETY: `dest` has been fully initialized by `imp::getrandom_inner`
    // since it returned `Ok`.
    Ok(unsafe { uninit.assume_init() })
}
````

I found that such a function was useful for applications that operate on byte arrays, e.g. HMAC keys, AES keys, TLS ClientHello/ServerHello `random` values, etc.

However, for other applications, I found the function way too limiting because Rust doesn't have an API equivalent to `impl<T, const M: usize, const N: usize> impl From<[T; M; N]` for `[[T; M]; N]`; i.e. there's no analog to `[T]::array_chunks()` for arrays. Further, it is error-prone to implement such conversions especially when we consider the possibility of `M * N` overflowing `isize::MAX`. Consequently, I think a secondary function is needed:

```rust
#[inline(always)]
pub fn getrandm_arrays<const M: usize, const N: usize>() -> Result<[[u8; N]; M], Error> {
    let mut uninit: MaybeUninit<[[u8; N]; M]> = MaybeUninit::uninit();
    // TODO: `uninit.as_bytes_mut()` when that is available.
    {
        // SAFETY: MaybeUninit<u8> is always valid, even for padding bytes
        let as_bytes_mut = unsafe {
            core::slice::from_raw_parts_mut(uninit.as_mut_ptr() as *mut MaybeUninit<u8>, 
            core::mem::size_of::<[[u8; N]; M]>()
            )
        };
        getrandom::getrandom_uninit(as_bytes_mut)?;
    }
    // SAFETY: `dest` has been fully initialized by `imp::getrandom_inner`
    // since it returned `Ok`.
    Ok(unsafe { uninit.assume_init() })
}
```

The the above two functions, I can efficiently implement everything I need, in a pretty type-safe way, without using `unsafe`, with minimal inconvenience, e.g. `let words = getrandm_arrays()?.map(|bytes| Wrapping(u64::from_ne_bytes(bytes)));`.

Notice in particular that the compiler should verify that `M * N` is within bounds, without us needing to do anything.

I've also considered doing more elaborate support for types that are "plain old data" or more generally which are safe to transmute from an array of arbitrary bytes of the same length:
```
pub unsafe trait Pod {}
unsafe impl Pod for u64 {}
unsafe impl Pod for u8 {}
unsafe impl<T: Pod, const N: usize> Pod for [T; N] {}

#[inline(always)]
pub fn getrandm_array_pod<T: Pod, const N: usize>() -> Result<[T; N], Error> {
    let mut uninit: MaybeUninit<[T; N]> = MaybeUninit::uninit();
    // TODO: `uninit.as_bytes_mut()` when that is available.
    {
        // SAFETY: MaybeUninit<u8> is always valid, even for padding bytes
        let as_bytes_mut = unsafe {
            core::slice::from_raw_parts_mut(uninit.as_mut_ptr() as *mut MaybeUninit<u8>, 
            core::mem::size_of::<[T; N]>()
            )
        };
        getrandom::getrandom_uninit(as_bytes_mut)?;
    }
    // SAFETY: `dest` has been fully initialized by `imp::getrandom_inner`
    // since it returned `Ok`.
    Ok(unsafe { uninit.assume_init() })
}
```

However, I found that at least Nightly Rustc didn't optimize uses of such a function any better than the equivalent that uses `getrandm_arrays()?.map(...)` to get the same effect without needing to introduce a `Pod` type abstraction. In fact, the currently Nightly Rust optimized this fancier version *worse*. [Godbolt link](https://rust.godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DEArgoKkl9ZATwDKjdAGFUtEywZ7HAGTwNMAHLuAEaYxHoADqgKhHYMLm4ekdGxAr7%2BQSyh4VyWmNa2AkIETMQECe6euVaYNnHFpQTpgSFheuaNFUnVJWXNmdkSAJSWqCbEyOwcAKQATADMYGDTAKwAQlSYTATjmBAsTACeoQD6Jgx%2BhCdMCifBhwSYCkOrACLTGgCCH59mmADU5nQIBA0wA7Gs2CwQQBZI6hOQXC4Wf4MdwggDqxCYEQifmA4Pe8zWPx%2BLAw/2AmAI2IY6FQLH%2B4JJX3%2BbP%2Bf0BBGBIChsPhmERlwI02JpNZ7IiJmCXNMNn%2B2GIxBIUCGLzFErZP3ZTIWqzWflofj2/gAbmEXit3pr/lKZVQGJTqbT6SwzkjCBB1LqAGwsEwEJnrOHHQUekXzJwmAAcouwbyG/wAtHH/gAlJ4mWgRpwQEYKpUkVPM7U69n8Yj/VT/PxVpkQ/4AKmrote/xDCPDIP8AHcILN1Wt69bPmX2QB5ADWqpeNsJpLBI5%2BdtlJnliuVxBnopZ3y%2BeBYEVo/wAYsqWKKnFSaYZXSCN0X5th/hWC5v67udQ6X%2BeICcQE6N50gy96FsQiYpk%2B/xCPkVAfqWY4wbQVDbnOi4LkuXxzPM%2BqGsaEBiD2RzPG8y7Si%2BjrXi6bqlNihyXmgDDmP8AQAWYeAAF6YHGebJqmGYKFmOb6jGO4sW8pBvo%2Bz4lja9CBv6gbnMKAEdmGwqXiJsbEuJVrFvMbZqUKyIgspyJ5juCH/AA9NZ/wACrjq844AdMPoaGZhAAHQ3HcDxPCcikWe5/w9ggjD/AQCDbDWCj/EwppMHQTDBPQXlWbJo5jjZdlCJ8J7YPZACaqkCsZhCXqJUF4HFhHEf8iVGugkmYOajqvhETDoPgRj/PcjwKFZOryfFtz9QFilMgZHJMUwmzwTa2X/GgxDsCAChGpMIJUOeJzYj2JydWUtxBZ5BA%2BSdAaHTSvE3E2k1GeGlXadgkkBLOWVjvOGqfWWVG3iBID/cBbpnQRY3%2BZdBDqielloSOOq2dB%2BWFSVTLuVg5huRo/zRXFoQRVQWa0IcNbIngYicZg6B9aT2MHhEILA66Jx%2BP4xDY1ZSMxAwkw1oGq07MQ/g09jU7Y%2BlNpThA5wKHNALMjNwoXYJbCs%2BZiaEh985YVherrHh/gEbQRGHCRelfCu37MzRSrEQxAjMTCbExFxkmMcxrEcq73FPrxkHPgJQmaesWliQEpE6TCElSRzUGZcN1L/JNZ2laG5XCaH6xVUOEd6VHkcydNj0qSAYODlzdmOc5rnuWdF1%2BQNgUBsFONhRFUUxTV8WJclqWYJLv0J9lSN5QVxVp52GmRlVz7d3VZsNZTzX/K1hMkLaXU9cAtMDUN7Ijb541Q1Nbay/LC2/UtK1rRteBbSAO0MntTAHUdBBQzL4YN4p11bomd1GwPTKk9GeL1JL7zHDfEEfJ1pUxOKgKgIIQ4kmztpXOkchzR3ztgCyi1sofSWt9T82VmaAzIaDcM4NG4TQDDDOGQ90I2lHijCe6MNCYxFCFPGfVMCE2JqTYUFMjRcRpvcdhDMmbOgBm6NmYRObMLsjzPmhB/iC3GCLdh4t3KDx1NLc%2B81Fb1xuKrTA6tPSa0XNrJhe5PgrgMQCG8qjlAUhLDYhxNZDzHhcTTV8JgfSSHgu42a80GbeIpK%2BLEOI8RGEqgE4sEIda/BCQCMJ/wfEvg3jGIJI4PFhMvPZACPj3aO0DF7diXFUwZNfPqey4c3g5PFN8fWBoGBGiNgvc2I4raUWkXSW2dFDoYAKUUjAJSmJlJdlTHiEF%2BKZmzCgupOk86vEkg%2BOOMlElySTinLs7YQHTycLU%2BpODT77PTl2MuVCK6KIck5Fy7DjEQybkFF4IV26Ok7oGeevcDD910eyYeY4WHjzRiXZEz1UzzxNvVRqeAV5r3ahvTq3V8S7yeJA/4h9nm0MDK2GactDFbKvtlaB61NprSfm6fah1Gifyec3Agf9bpxSAQGc5U8IVgLjBA/BUCSBrVgT7BBSDQSRmOcswueCSVjkIdlYhmKKFSKAizMGR9IaMvoT9HUSTEa5VYWjbGnDsa4zugTdqAiyaxEpqI2mEjDzKpdM/ORHN3KV0BH4FRAtqQaOploycEsrL6JSR%2BJWyIVbuDMcKXiWsMJNOwrhNp%2BEzQWlIpbci34/jXDtmbf2czBILPFesKJuJ8RxMkHGMSPoY7rISSQtkI0ewkHQHFfFNts10QUBZeYJ4vIHAiBAcEThj5Dv%2BCWmJwAZYBO2rtfwNCu3HzVDc360sm3EBbdYzCzScIGyTUbFN4E012IzY6LNtEjhDPQHmqCQdC1HOLdiUtsSZ7xKfFWmtYE61BunO289hxL3dpPJun4HARi0E4CsXgngOBaFIKgTgaYzCBgUGMCYCsFg8FIAQTQoGRiThAPMMEXkACckh5hcBWNGMEXBZhgg0ORyQKx9CcEkFBnDcHOC8AUCADQWGcMjDgLAJAaBDx0DCOQSgIm8T0HCBcYACACAkz4HQR4xBuMQGCOx4IfhSiHE4JhkTbBBDjjaXpmDvAsAHCMOIczpB8CrTqOabjtnMCqFqAGKYmG/CPHA7Zo0wRsTEEOC4LA7GaQHn06BvgBhgAKAAGp4EwD2ccERGCRZkIIEQYh2BSAy/IJQah2O6FyAYIwIBTDmH0HgYI3HIAjFQBEQoTFOBJicEtJaDWCBJnoOaWgrZ5hcfyLUJrDg6RdCqLMUgPhjQDDaCsJjUQYhNfGxISbi3UgMH6K0cI828gFHqL0corhKirb28Ng7jQttZDm0xjoZQVs0csIdq7gx5sjBQ%2BMLauQaR8Mi2BiDbHbPwY4BVggyBUR4Hk4p0mEBEOVYVPgIglZsK5H%2BC4UTMndTkaGLwbD5m1SkHwwsLy0ZiPkbJ1wSnPo6OTd86x0g0HYPA64zxvj%2BPSCCcQCAMYBApQWAoBAKTYniABFYFMUH4OuBeQCV5WD1NCAkHhXofgmXRDiFyyr/LKh1C2eK6QHsj6/vMY4JBhn7HgfjgDHz/4iC1FIfB3JhTJN/gQHR9JsIWOuA47Z1oAn%2BH5jRi8lwH08wAnRi4GCFYPpZg%2Bh9ExungOmeccsKzvHvv/scFmIn3gzOfe4dIOaNTcQQCSCAA).

Therefore, I propose we implement (only) `getrandom_array` and `getrandom_arrays` as definied above. I am definitely open to better names.

As far as MSRV goes, I persoally would prefer to set the MSRV to 1.51. However, if that's too drastic, I suggest we add a `rust_1_51` feature or similar that guards this and any other feature that may require later versions of Rust. I think this would be easy enough for us to maintain.

**Comment by briansmith** [comment]
Also, I found that `getrandom_array` and `getrandom_arrays` must be inlined to produce the code we expect, which is why I suggest `#[always(inline)]`.

**Comment by briansmith** [comment]
> `// SAFETY: MaybeUninit<u8> is always valid, even for padding bytes`

I copied those comments from `as_bytes_mut()` but they don't make as much sense in this context. Also, those comments should emphasize `The Rust compiler is responsible for enforcing `N <= isize::MAX`  (and `M <= isize::MAX`) when it typechecks since this function uses `N` (and `M`) as the size of a slice in its signature."

**Comment by briansmith** [comment]
Draft PR #293 builds on PR #291 to add a single `getrandom_array` function that subsumes all of the variants `gerandom_array`, `getrandom_arrays`, and `getrandom_arrays_pod` I mentioned above. It does use a generic `Pod`-like type, but only to allow arbitrary levels of byte array nesting, e.g. `[[[u8; 4]; 4]; 16]`.

**Comment by briansmith** [comment]
Now I've reconsidered my comments above. I think that having generic functions like this in `getrandom` is better avoided. Almost all uses of this can be use something like `zerocopy::FromBytes` to get similar effects, with just a slight amount of clumsiness. So I think we should just close this as "Not Planned."

**Comment by josephlr** [comment]
@briansmith sounds good! And I agree, future integration or compatibility with `zerocopy` seems like the best bet.
