### ISSUE TITLE
"All entropy sources failed" on wasm32-wasi

### ISSUE THREAD

**Issue by devsnek** [rust-random/getrandom#34]
A project i'm trying to build fails with `All entropy sources failed (permanently unavailable); cause: OsRng: support for wasm32 requires emscripten, stdweb or wasm-bindgen (permanently unavailable)`, though `getrandom` says it supports `__wasi_random_get`

**Comment by newpavlov** [comment]
Looks like you are not building for WASI target (note: WASM is like CPU architecture and WASI is in a certain sense an operating system, so the first does not necessarily imply the second). Depending on that you use, enable `stdweb` or `wasm-bindgen` feature for `getrandom` crate. You can do it be adding this line to your project's `Cargo.toml` dependencies section:
```toml
getrandom = { version = "*", features = ["wasm-bindgen"] }
```

**Comment by devsnek** [comment]
i'm doing `cargo build --target wasm32-unknown-wasi`. (and I'm aware what WASI is to WASM)

**Comment by dhardy** [comment]
As I said in the other issue, use the target `wasm32-wasi` (check the changelog).

**Comment by devsnek** [comment]
updating to rustc beta and using `wasm32-wasi` produces the same error.

**Comment by newpavlov** [comment]
Hm, this is strange... I can't find from where this error comes. Search does not show any code in this and `rand` repository which produce it. What versions of `getrandom`/`rand` do you use? Have you tried to use `getrandom` directly?

Note that `getrandom` is used only since `rand v0.7` and `rand_os v0.2`, and IIRC earlier versions of those crates did not support WASI.

**Comment by devsnek** [comment]
using `rand 0.7.0-pre.1` worked.
