### ISSUE TITLE
Should __getrandom_custom use "Rust" ABI?

### ISSUE THREAD

**Issue by josephlr** [rust-random/getrandom#345]
Right now, the implementation of the `custom` feature uses a `#[no_mangle]` function named `__getrandom_custom` with signature: `extern "C" fn(*mut u8, usize) -> u32`. 

When implementing this feature in #109, I initially used the `extern "Rust"` ABI, but after some discussion, [we decided to use `extern "C"`](https://github.com/rust-random/getrandom/pull/109#issuecomment-542582294)  due to issues around the stability of the `"Rust"` ABI.

However, @LegionMammal978 noted in https://github.com/rust-random/getrandom/pull/341#issue-1615581546 that panicking across an `extern "C"` function is unsafe, and it's very possible that a custom implementation could panic (certainly we do nothing to prevent that).

So should we switch to using the `"Rust"` ABI?  If so, should we continue passing a raw pointer/length pair, or pass a slice?

**Comment by newpavlov** [comment]
Panic safety is a strong argument for using the `"Rust"` ABI. I think we can start with the minimal change of switching to it (i.e. we still will use `fn(*mut u8, usize) -> u32` as signature). In hypothetical `v0.3` we may expose `__getrandom_custom` with slice-based signature instead of relying on the macro.

**Comment by notgull** [comment]
In theory, you could also catch the panic and either abort on it or pass it around later as an error.

**Comment by LegionMammal978** [comment]
The ABI instability of `extern "Rust"` could be an issue here. Nothing's stopping `__getrandom_custom()` from being defined in a `cdylib` compiled with a different compiler version than the final program using `getrandom_inner()`. That would make it UB to call the `extern "Rust"` function across the boundary.

Catching the panic is not all that difficult. It can be done most easily with a drop guard that causes a double panic:
```rust
extern "C" fn example() -> Output {
    struct PanicOnDrop;
    impl Drop for PanicOnDrop {
        fn drop(&mut self) {
            panic!("callback panicked");
        }
    }
    let guard = PanicOnDrop;
    let output = callback();
    core::mem::forget(guard);
    output
}
```

It would be a lot trickier to pass the full payload across the boundary, since, as before, neither a full `Box<dyn Any + Send + Sync>` nor a formatted `String` would be compatible across a `cdylib`. But just to continue the panic without the same payload would be feasible, by turning the panic into an error code and panicking again.
