### ISSUE TITLE
Use getrandom on FreeBSD

### ISSUE THREAD

**Issue by myfreeweb** [rust-random/getrandom#35]
[`getentropy` in libc](https://github.com/freebsd/freebsd/blob/master/lib/libc/gen/getentropy.c) uses `sysctl` only as a fallback and uses the `getrandom` syscall if available.

This crate should check for `getrandom` via `dlopen` and use it if available.

**Comment by josephlr** [comment]
Is there a good reason to add this? If we have to keep the sysctl approach around regardless, it just seems like more maintenance to maintain two equivalent implementations for FreeBSD.

**Comment by myfreeweb** [comment]
The sysctl is slower and does not block by itself (as in, it would occasionally return less bytes and your current code would return an error, it [must be used in a loop](https://github.com/freebsd/freebsd/blob/d946d8f14c81df5c94524f0c759db84880bbcae8/lib/libc/gen/getentropy.c#L64-L71))

**Comment by josephlr** [comment]
> The sysctl is slower

So it looks like the only reason this is true is because the sysctl only allows up to 256 bytes per call, while the getrandom syscall allows very large reads per call. This only seems relevant if we are bottlenecked by the ring transition overhead. Are there any metrics on this?

> and does not block by itself (as in, it would occasionally return less bytes and your current code would return an error, it must be used in a loop)

Good catch, fixed in: #36 

Looking at [FreeBSD's `getrandom(2)` man page](https://www.freebsd.org/cgi/man.cgi?query=getrandom&apropos=0&sektion=0&manpath=FreeBSD+12.0-stable&arch=default&format=html#end), it would seem that we would have to do this loop regardless, as it does not guarantee the completion of large buffer requests.

@myfreeweb to do this we need to add libc related bindings (this was done for Linux in https://github.com/rust-lang/libc/pull/1399). Is there a better way to detect if the syscall is supported? On Linux, this is indicated by the syscall returning ENOSYS, does FreeBSD do something similar?

**Comment by myfreeweb** [comment]
Do not call the syscall directly, FreeBSD's public ABI is the libc.

Just do what you're doing on Illumos:

https://github.com/rust-random/getrandom/blob/0b87a0974b75357d55d6ec2c0358a81371294716/src/solaris_illumos.rs#L93

**Comment by newpavlov** [comment]
@myfreeweb 
Can you prepare PR with suggested changes?
