### ISSUE TITLE
`libc` `v0.2.154` yanked

### ISSUE THREAD

**Issue by ratankaliani** [rust-random/getrandom#423]
The most recent release of `getrandom` (v0.2.15) is dependent on `libc` ^0.2.154, which has been yanked from crates.io: https://crates.io/crates/libc/0.2.154. `libc` should be downgraded to a version that is still on `crates.io`, 0.2.153.

Projects that are dependent on `getrandom` need to downgrade to a previous version of `getrandom` (ex. v0.2.14) to avoid seeing the following:

```bash
Updating crates.io index
error: failed to select a version for the requirement `libc = "^0.2.154"`
candidate versions found which didn't match: 0.2.153, 0.2.152, 0.2.151, ...
location searched: crates.io index
required by package `getrandom v0.2.15`
    ... which satisfies dependency `getrandom = "^0.2.15"` of package ...`
    ... which satisfies git dependency ... of package ... 
    (/home/runner/_work/...)`
perhaps a crate was updated and forgotten to be re-vendored
```

**Comment by newpavlov** [comment]
Version of `libc` was bumped in #411. Downgrading it would break the Dragonfly support, but I guess it's a lesser of two evils. Is there a chance that v0.2.155 will be published in a day or two? If yes, it's probably better to wait for fix on their side, otherwise publishing `getrandom` version with downgraded `libc` will be an acceptable workaround for now.

**Comment by newpavlov** [comment]
`libc` v0.2.155 has been published, so I think we can close this issue,
