### ISSUE TITLE
Documentation and examples for __getrandom_v03_custom?

### ISSUE THREAD

**Issue by juh9870** [rust-random/getrandom#549]
In the upcoming v0.3, the `getrandom::register_custom_getrandom` macro is replaced with an unsafe `__getrandom_v03_custom` function, and for the users that are not familiar with unsafe Rust and raw pointer mangling, this might be a bit daunting.

Would be nice to have an example or two showcasing how to properly implement it (and maybe even an example to bridge it to the `Fn(&mut [u8]) -> Result<(), getrandom::Error>`, which was used for macro in 0.2).

**Comment by newpavlov** [comment]
How about something like this?

The function accepts a pointer to a buffer that should be filled with random data and its length in bytes. Note that the buffer MAY be uninitialized. On success, the function should return `Ok(())` and fully fill the input buffer; otherwise, it should return an error value.

While wrapping functions which work with byte slices you should fully initialize the buffer before passing it to the function:
```rust
use getrandom::Error;

fn my_entropy_source(buf: &mut [u8]) -> Result<(), getrandom::Error> {
    // ...
    Ok(())
}

#[no_mangle]
unsafe extern "Rust" fn __getrandom_v03_custom(
    dest: *mut u8,
    len: usize,
) -> Result<(), Error> {
    let buf = unsafe {
        // fill the buffer with zeros
        core::ptr::write_bytes(dest, 0, len);
        // create mutable byte slice
        core::slice::from_raw_parts_mut(dest, len)
    };
    my_entropy_source()
}
```

**Comment by juh9870** [comment]
Yeah, something like that would be good to have in the docs

**Comment by juh9870** [comment]
Forgot to ask, what are guarantees about the `dest: *mut u8` pointer? Is it guaranteed to be valid and aligned?

**Comment by newpavlov** [comment]
`*mut u8` pointers are always aligned and yes it's valid for writes up to `len` bytes.
