### ISSUE TITLE
SecureZeroMemory with RtlGenRandom and Warnings

### ISSUE THREAD

**Issue by 0xSilene** [rust-random/getrandom#70]
Not sure if this is the correct place to discuss this or whether this is a problem at all.

In Microsoft's documentation for [RtlGenRandom](https://docs.microsoft.com/en-us/windows/win32/api/ntsecapi/nf-ntsecapi-rtlgenrandom), it states:

> When you have finished using the random number, free the RandomBuffer buffer by calling the [SecureZeroMemory](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/aa366877) function.

Is this done/called automatically in this crate?

Also, it has a warning:

> The RtlGenRandom function is available for use in the operating systems specified in the Requirements section. It may be altered or unavailable in subsequent versions. Instead, use the CryptGenRandom function.

And CryptGenRandom is deprecated. I already read the issue thread about why you don't want to use BCryptGenRandom rn because it doesn't support Windows XP, but I honestly think the change should be made soon. BCryptGenRandom works on minimum of Windows Vista.

**Comment by josephlr** [comment]
> Is this done/called automatically in this crate

Nope, this crate specifically implements one function:
```rust
pub fn getrandom(dest: &mut [u8]) -> Result<(), Error>
```
and that's it. Things like `SecureZeroMemory` are orthogonal to this crate, and would be be handled by a "Secure Buffer Mangement" crate like [`secstr`](https://crates.io/crates/secstr). As that crate's [`SecVec<u8>`](https://docs.rs/secstr/0.3.2/secstr/struct.SecVec.html) implements `BorrowMut<[u8]>`, it can be used with getrandom like any array or vector.

Both securely managing secrets in memory and generating good random bytes are tricky problems, but they are different problems. Keeping them in separate crates seems to be the best bet.

> And CryptGenRandom is deprecated. I already read the issue thread about why you don't want to use BCryptGenRandom rn because it doesn't support Windows XP, but I honestly think the change should be made soon. BCryptGenRandom works on minimum of Windows Vista.

I think discussion around this are best handled in #65 (so that everyone involved will see it).

**Comment by newpavlov** [comment]
Regarding deprecation of `RtlGenRandom` see this [message](https://github.com/rust-random/rand/issues/111#issuecomment-316140155). There is a proposal to use `getrandom` inside `std`, so as long as Windows XP (and preferably Vista) support is not officially dropped by Rust, we have to stay conservative.

I think we can close this issue in favor of #65?

**Comment by 0xSilene** [comment]
Yes, I'll close the issue and any further discussion can be done on #65
